/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TempCardTestRouteImport } from './routes/temp-card-test'
import { Route as ApiPublicPaymentsMercadopagoWebhookRouteImport } from './routes/api/public/payments/mercadopago/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TempCardTestRoute = TempCardTestRouteImport.update({
  id: '/temp-card-test',
  path: '/temp-card-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsMercadopagoWebhookRoute =
  ApiPublicPaymentsMercadopagoWebhookRouteImport.update({
    id: '/api/public/payments/mercadopago/webhook',
    path: '/api/public/payments/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/temp-card-test': typeof TempCardTestRoute
  '/api/public/payments/mercadopago/webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/temp-card-test': typeof TempCardTestRoute
  '/api/public/payments/mercadopago/webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/temp-card-test': typeof TempCardTestRoute
  '/api/public/payments/mercadopago/webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/temp-card-test'
    | '/api/public/payments/mercadopago/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/temp-card-test'
    | '/api/public/payments/mercadopago/webhook'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/temp-card-test'
    | '/api/public/payments/mercadopago/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TempCardTestRoute: typeof TempCardTestRoute
  ApiPublicPaymentsMercadopagoWebhookRoute: typeof ApiPublicPaymentsMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temp-card-test': {
      id: '/temp-card-test'
      path: '/temp-card-test'
      fullPath: '/temp-card-test'
      preLoaderRoute: typeof TempCardTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mercadopago/webhook': {
      id: '/api/public/payments/mercadopago/webhook'
      path: '/api/public/payments/mercadopago/webhook'
      fullPath: '/api/public/payments/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TempCardTestRoute: TempCardTestRoute,
  ApiPublicPaymentsMercadopagoWebhookRoute:
    ApiPublicPaymentsMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
